language: node_js

node_js: 
  - "0.10"
  - "0.11"
  - "0.12"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - bower install
  - npm test
  - npm run mocha
  - npm run jasmine
  - npm run karma-jasmine
  - npm run karma-mocha
  - npm run gulp karma.jquery
  - npm run protractor
